language: python
python:
  - "3.6"

branches:
  only:
    - master

before_install:
  - pip install -r requirements.txt
  - pip install --upgrade https://github.com/ozgur/python-linkedin/tarball/master

script:
  - python test.py

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on:
    branch: master
    repo: Tweetsched/tweetsched-linkedin-publisher

notifications:
  email:
    on_success: never
    on_failure: always
